name: workflow-for on premise server

on: 
  push:

jobs:
  TEST-JOB:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List all files
        run: ls -a

      - name: Print hello
        run: echo "hello world" >> hello.txt

  # This job will test permissions
  build-job:
    needs: [TEST-JOB]
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check permissions on directory
        run: ls -lrt
